modLoader="javafml"
loaderVersion="[47,)"
license="Custom license"

[[mods]]
modId="dark_mist_dweller"
version="0.0.1"
displayName="Dark Mist Dweller"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="UberUser, MCreator"
description="Somewhere in the dark we remain"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.dark_mist_dweller]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration